
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

name: Docker

jobs:

  build-docker-image:

    strategy:
      fail-fast: false

      matrix:
        include:
          - image_name: base
            tag_prefix: ''
          - image_name: app
            tag_prefix: app_          
          
    runs-on: ubuntu-latest
    
    name: ${{ matrix.image_name }} 
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R from public RSPM
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R package and external library dependnencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dapperstats/shinydocker
          tags: |
            type=raw,value=${{ matrix.tag_prefix }}latest
            type=semver,pattern={{raw}},prefix=${{ matrix.tag_prefix }}  

      - name: Build and push ${{ matrix.image_name }} image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          build-args: |
            "event_sha=${{ github.sha }}"
            "image_name=${{ matrix.image_name }}"

      - name: Deploy app
        if: ${{ matrix.image_name == 'app' }}
#        if: ${{ matrix.image_name == 'app' && github.event_name == 'release'}}        
        run: |
           docker run --rm dapperstats/shinydocker:app_latest -e "SHINY_ACCOUNT=${{ secrets.SHINY_ACCOUNT }}"

#           -e "SHINY_TOKEN=${{ secrets.SHINY_TOKEN }}" -e "SHINY_SECRET=${{ secrets.SHINY_SECRET }}"